packages:
  - apps/*
  - libs/core/*
  - libs/shared/*
  - libs/features/*
  - tools
onlyBuiltDependencies:
  - core-js
  - esbuild
  - '@swc/core'
overrides:
  react: ^18.3.1
  react-dom: ^18.3.1
sharedWorkspaceLockFile: true
strictPeerDependencies: true
