packages:
  - apps/*
  - libs/core/*
  - libs/shared/*
  - libs/features/*
onlyBuiltDependencies:
  - core-js
  - esbuild
overrides:
  react: ^18.3.1
  react-dom: ^18.3.1
sharedWorkspaceLockFile: true
strictPeerDependencies: true
