packages:
    - apps/*
    - libs/core/*
    - libs/shared/*
    - libs/features/*
    - tools
onlyBuiltDependencies:
    - core-js
    - esbuild
    - '@swc/core'
overrides:
    react: ^19.0.0
    react-dom: ^19.0.0
sharedWorkspaceLockFile: true
strictPeerDependencies: true
