packages:
  - apps/*
  - libs/core/*
  - libs/shared/*
  - libs/features/*
  - tools
  - support/*
  - docs
ignoredBuiltDependencies:
  - puppeteer
onlyBuiltDependencies:
  - core-js
  - esbuild
  - '@swc/core'
overrides:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@unity/features.workload-viewer@1.0.0>react": 17.0.2
  "@unity/features.workload-viewer@1.0.0>react-dom": 17.0.2
sharedWorkspaceLockFile: true
strictPeerDependencies: true
